[package]
name = "rcli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
chacha20poly1305 = "0.10.1"
clap = { version = "4.5.16", features = ["derive"] }
enum_dispatch = "0.3.13"
